openapi: 3.0.0
info:
  title: Optional Score API for Flappy Birds
  version: 1.0.0
paths:
  /scores:
    get:
      summary: Get top scores (optional)
      responses:
        '200':
          description: OK
    post:
      summary: Submit a score (optional)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                score:
                  type: integer
      responses:
        '201':
          description: Created
